name: RELEASE | build, test and create jar

on:
  push:
    branches: 
      - 'release/*'
  pull_request:
    branches:
      - 'release/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr 'release/' '')"
      id: extract_branch
  
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - uses: actions/upload-artifact@v3
      with: 
        name: BLACKJACK-${{ steps.extract_branch.outputs.branch }}-SNAPSHOT
        path: build/libs/
