name: Close release

on:
  issues:
    types: [closed]

jobs:
  close-release:
      name: "Close release"
      runs-on: ubuntu-latest
      if: startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release')
      steps:
      
        - name: Extract release version
          shell: bash
          run: |
            TITLE="${{ github.event.issue.title }}"
            VERSION=${TITLE#Release }
            echo "##[set-output name=version;]$(echo $VERSION)"
          id: extract_release_version
      
        - uses: actions/checkout@v3
          with: 
            ref: "release/${{ steps.extract_release_version.outputs.version }}"
            
        - name: Initialize mandatory git config
          run: |
            git config user.name "GitHub Web Flow"
            git config user.email "actions@github.com"
            git config --global --add safe.directory /github/workspace
        
        - name: Merge release to main
          run: |
              git fetch --unshallow
              git checkout main
              git pull
              git merge --no-ff release/${{ steps.extract_release_version.outputs.version }} -m "Auto-merge release to main"
              git push

        - name: Merge release to develop
          run: |
              git fetch --unshallow
              git checkout develop
              git pull
              git merge --no-ff release/${{ steps.extract_release_version.outputs.version }} -m "Auto-merge release to develop"
              git push
