name: Close release main

on:
  issues:
    types: [closed]

jobs:
  auto-merge-main:
      name: "Close release main"
      runs-on: ubuntu-latest
      if: startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release')
      
      steps:
      
        - name: Extract release version
          shell: bash
          run: |
            TITLE="${{ github.event.issue.title }}"
            VERSION=${TITLE#Release }
            echo "##[set-output name=version;]$(echo $VERSION)"
          id: extract_release_version
      
        - uses: actions/checkout@v3
          with: 
            ref: "release/${{ steps.extract_release_version.outputs.version }}"
            
        - name: Initialize mandatory git config
          run: |
            git config user.name "GitHub Web Flow"
            git config user.email "actions@github.com"
            git config --global --add safe.directory /github/workspace
                
        - name: create pull request for main
          id: open-pr-main
          uses: repo-sync/pull-request@v2.11
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_branch: "release/${{ steps.extract_release_version.outputs.version }}"
            destination_branch: main
            pr_title: "auto merge main"
            pr_body: "auto merge main"
            pr_draft: true
            pr_allow_empty: true
            
        - name: enable automerge for main
          if: steps.open-pr-main.outputs.pr_number != ''
          uses: peter-evans/enable-pull-request-automerge@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            pull-request-number: ${{ steps.open-pr-main.outputs.pr_number }}
            merge-method: merge


  auto-merge-develop:
    needs: auto-merge-main
    name: "Close release develop"
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release')

    steps:

      - name: Extract release version
        shell: bash
        run: |
          TITLE="${{ github.event.issue.title }}"
          VERSION=${TITLE#Release }
          echo "##[set-output name=version;]$(echo $VERSION)"
        id: extract_release_version

      - uses: actions/checkout@v3
        with: 
          ref: "release/${{ steps.extract_release_version.outputs.version }}"

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Web Flow"
          git config user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: create pull request for develop
        id: open-pr-develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "release/${{ steps.extract_release_version.outputs.version }}"
          destination_branch: develop
          pr_title: "auto merge develop"
          pr_body: "auto merge develop"
          pr_draft: true
          pr_allow_empty: true

      - name: enable automerge for develop
        if: steps.open-pr-develop.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr-develop.outputs.pr_number }}
          merge-method: merge
            
            
  create-release:
    needs: auto-merge-develop
    name: "create release"
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release')

    steps:

      - name: Extract release version
        shell: bash
        run: |
          TITLE="${{ github.event.issue.title }}"
          VERSION=${TITLE#Release }
          echo "##[set-output name=version;]$(echo $VERSION)"
        id: extract_release_version

      - uses: actions/checkout@v3
        with: 
          ref: "release/${{ steps.extract_release_version.outputs.version }}"

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Web Flow"
          git config user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace          
            
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: BLACKJACK-${{ steps.extract_branch.outputs.branch }}
          path: artifacts/
          
      - name: Push new branch
        run: |
          git add .
          git commit -m "create artifact"
          git push origin release/${{ steps.extract_release_version.outputs.version }}

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          tag: "release/${{ steps.extract_release_version.outputs.version }}"
          artifacts: "artifacts/BLACKJACK-${{ steps.extract_release_version.outputs.version }}.zip"
