name: Create new release

on:
  issues:
    types: [opened, labeled]

jobs:
  create-new-release:
      name: "Create new release"
      runs-on: ubuntu-latest
      if: startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release')
      steps:
        - uses: actions/checkout@v3

        - name: Extract version from issue title
          run: |
            TITLE="${{ github.event.issue.title }}"
            VERSION=${TITLE#Release }
            echo "::set-env name=RELEASE_VERSION::$VERSION"
            
        - name: Extract branch name
          shell: bash
          run: |
            TITLE="${{ github.event.issue.title }}"
            VERSION=${TITLE#Release }
            echo "##[set-output name=version;]$(echo $VERSION)"
          id: extract_release_version

        - name: Create release branch
          run: git checkout -b release/${{ steps.extract_release_version.outputs.version }}

        - name: Initialize mandatory git config
          run: |
            git config user.name "GitHub ACTION"
            git config user.email "noreply@github.com"

        - name: Change version in gradle.properties
          run: |
            echo "CUR_VERSION=${{ steps.extract_release_version.outputs.version }}" > ~/gradle.properties

        - name: Push new branch
          run: git push origin release/${{ steps.extract_release_version.outputs.version }}
